### ISSUE TITLE
on('subscribe' listener isn't fetching weather data

### ISSUE THREAD

**Issue by blake-haas** [RodgerLeblanc/Custom-Weather#1]
The event listener for subscribe event is setting the response to ninjacell.

The problem is that until the schedule event fires, this will be on the watch face for up to an hour or more depending on the settings the user provided.  Wouldn't it be a better idea to fetch the weather right when it subscribes?

**Comment by RodgerLeblanc** [comment]
Yes, it's always better to do so, in fact t you can probably see in the GitHub history that previous  commit was done that way. Unfortunately, Yahoo Weather query sometimes hang, and if it does while subscribing, the user who's subscribing while receive a "503 service unavailable" message on phone and the stream will fail to subscribe, meaning that there won't be anything displayed on watch and nor on schedule or on webhook event will be able to update the watch. That's why I came with this "subscribe successfully and manually call webhook" solution. OpenWeatherMap url doesn't have this issue, only Yahoo Weather url, and only on real device subscription scenario, the simulator always subscribe successfully no matter what. You can test it yourself by copying the previous commit code and creating your own stream, publish privately and install the stream on your watch. In the stream setup, make sure to choose Yahoo as the service provider. Sometimes it will work, sometimes it won't. I should add something in on webhook section to avoid refreshing weather info for users who's weather info are not older than an hour, because every new stream that gets added will refresh weather for everyone, and I might face an issue where my OpenWeatherMap API key will be called too frequently... That's on my to-do list. Lete know if you have another idea on how I can handle this differently. I'm always open to suggestions.                                                                                                                                                                         -- Roger Leblanc CEO, receptionist and janitor at CellNinja.cam: +1 807 355 2627 | t: +1 819 840 9428 | @RodgerLeblanc                                                                                                                                                                            From: notifications@github.comSent: December 28, 2016 1:45 PMTo: Custom-Weather@noreply.github.comReply-to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: [RodgerLeblanc/Custom-Weather] on('subscribe' listener isn't fetching weather data (#1)  The event listener for subscribe event is setting the response to ninjacell.
The problem is that until the schedule event fires, this will be on the watch face for up to an hour or more depending on the settings the user provided.  Wouldn't it be a better idea to fetch the weather right when it subscribes?

**Comment by RodgerLeblanc** [comment]
Commit f9f492219104ab37c77b6d19d7c6cd9512fb8441 fixes this issue.
